<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MatchController;
use Illuminate\Support\Facades\DB; // 👈 1. Import the DB facade

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// 2. Updated root route using DB query to fetch row 1 directly
Route::get('/', function () {
    $notification = DB::table('notifications')
        ->where('notification_id', 1)
        ->first(); 

    return view('welcome', compact('notification'));
});

// Match Controller Route (kept if you need it elsewhere)
Route::get('/match-details', [MatchController::class, 'showLastMatch']);

// Dashboard (Protected)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Home (Protected)
Route::get('/home', function () {
    return view('auth.home');
})->middleware(['auth', 'verified'])->name('home');

// Profile View (Protected)
Route::get('/pf', function() {
    return view('auth.profile');
})->middleware(['auth', 'verified'])->name('pf');

// User Profile Management (Protected Group)
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Authentication Routes generated by Breeze/Jetstream
require __DIR__.'/auth.php';